name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://reducecropfailure.onrender.com/

    steps:
      - name: Deployment recorded
        run: echo "Production deployment is live"
